on:
  push:
  pull_request:
    types: [opened]

name: Rust

jobs:
  ci:
    name: CI Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [--all-features]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy, llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@v1
        with:
          tool: nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: ${{ matrix.features }} -- -D warnings

      - name: Run library tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run ${{ matrix.features }}

      - name: Run doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

      - name: Collect coverage data
        run: cargo llvm-cov nextest --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
